### ISSUE TITLE
Show RPATHs?

### ISSUE THREAD

**Issue by asmaloney** [kwin/macdependency#10]
Thanks for this - just helped me track down an issue!

One thing that would be useful would be to show all the RPATHS for a given executable/dylib in the interface somewhere instead of having to flip back-and-forth to `otool` on the command line for them.

**Comment by kwin** [comment]
This has been fixed with https://github.com/kwin/macdependency/commit/5696c282b73171788548fc6398b39e390f0e2dc2 quite some time ago. You just need to wait for a release.

**Comment by asmaloney** [comment]
Awesome - thanks!  I sort of thought the project might be dead since the last release was 7 years ago...

Look forward to the next release.
