### ISSUE TITLE
Integrate with Travis CI

### ISSUE THREAD

**Issue by kwin** [kwin/macdependency#4]
Objective C is supported: http://docs.travis-ci.com/user/languages/objective-c/ (should be used for at least for Macdependency submodule).

**Comment by mike-lischke** [comment]
Hi, I'm currently reworking MacDependency in my fork to make it run properly on macOS Sierra (upgrade to latest compiler, enable C++11, use ARC, remove boost, add custom icon etc.), however I need some clarifications regarding the code license. Currently there is no explicit license attached. Are you ok if I attach one (GPL)? Please contact me via my profile -> homepage, if you like to discuss things in private. Thanks.

**Comment by kwin** [comment]
Hi @mike-lischke,
great to hear that. I will later on clarify the license (it is indeed GPLv3). Would you mind just creating a PR with your changes, then I will happily apply. I must admit that I didn't spend much time on developing macdependency any further in the last years, but I am definitely interested in integrating high quality patches. That would be a lot better than creating forks of it. WDYT?

**Comment by mike-lischke** [comment]
Ok, fine. I plan to add a copyright header to all files. Travis integration is done now and I have removed the images + Qt branches [in my fork](https://github.com/mike-lischke/macdependency). If that is ok for you then I can create a PR yet today.

**Comment by kwin** [comment]
Perfect, having the images folder in the master branch is no problem (and eases forking, creating PRs). The images and qt branches on my repo should not be affected by your PR anyways (since your PR will only target master).

**Comment by kwin** [comment]
The travis issue was fixed with https://github.com/kwin/macdependency/commit/c09bf0d732e129f1c08d79b97ff2e18f1c6a5180.

**Comment by mike-lischke** [comment]
@kwin You might want to change the link to the Travis CI image to use your own account (in the readme).

**Comment by kwin** [comment]
Thanks for the hint, just did that.
