### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by alexchandel** [kwin/macdependency#7]
Could we get a 1.0.1 release build?

**Comment by kwin** [comment]
The next release will be 1.1 due to the massive amount of changes done by @mike-lischke.

**Comment by kwin** [comment]
I just published 1.1.0. Please download from https://github.com/kwin/macdependency/releases.

**Comment by alexchandel** [comment]
You ought to add a formula for this to https://github.com/Homebrew/homebrew-core/ .
